### PR TITLE
Navigation Drawer - Bounty #107

### PR DESCRIPTION
**Pull request by arandr**
https://assembly.com/kanshu/bounties/107

Added the contents of the drawer. Was not sure how backend API was going to work, so I didn't add the user picture to the global user data, it's just being read when creating the drawer from its layout.
Signout icon wasn't in the main repo, so I extracted it from the mock-up myself -- we may want to change it for the real icons if possible.

### CODE REVIEW

**Comment by intrications** [comment]
Please remove the images you aren't using.

For example, you don't seem to using all these size of image - just the 36dp: 

ic_assignment_black_18dp.png
ic_assignment_black_24dp.png
ic_assignment_black_36dp.png
ic_assignment_black_48dp.png

**Comment by intrications** [comment]
1. Left align the menu text like in the mockup: https://www.dropbox.com/s/749aqrtc5p9n6ne/02a%20Kanshu%20UI%20-%20drawer%20screen.png?dl=0

The menu text also should be vertically centered to the icons. This isn't what the mockup shows but I personally think would be better, so let me know if you disagree.

2. The status bar needs to be made transparent (on Lollipop and perhaps KitKat) - again to match the mockup, but also Google's design guidelines. Do you have a device running Lollipop that you can test on? Otherwise, of course, you will have to use the emulator.

**Comment by arandr** [comment]
Fixed the images and menu and added translucency.

**Comment by intrications** [comment]
Thanks. I may a few changes to adjust to the correct status bar size.

I think it also needs testing on Android pre-Lollipop but I will do that and make any fixes.

Thanks!

**Pull request merged**
