### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by vsima**
- removed duplicate com.kanshu.kanshu base package name and renamed to com.kanshu.android
- removed v21 method signature onCreate() and updated dependent classes
- added package names for activity, fragment, widget(for layouts & widgets), and adapters
- renamed Model package name to model
- everything builds and tests run!

### CODE REVIEW

**Comment by intrications** [comment]
Thanks.

I will probably merge this. I agree with the package name changes.

However, I first want to check no-one is very close to submitting a bounty. It would be unfair to expect them to merge in these changes at the last minute. And I suspect if they tried Model would end up with a capital letter again!

Of course the tests run because there aren't any! That is something that needs to be fixed but I don't have much experience with tests on Android. Do you?

**Comment by vsima** [comment]
Now that I look back this is a little much to merge right now. These
commits should be split up. Feel free to reject for now.

**Comment by vsima** [comment]
Yes. I'll setup the tests this week.

**Comment by intrications** [comment]
@vsima I've just looked through the bounties and we'll be ok to merge it soon.

But I do agree. A few smaller merges would make it much clearer.

**Comment by intrications** [comment]
That's great. I'll set up a bounty for the tests so you get credited for it.

**Comment by intrications** [comment]
The "removed v21 method signature onCreate() and updated dependent classes" is definitely something that needs to be fixed asap, if you can send a pull request for that. Otherwise, I can make the change but I'd rather you got the credit for it.

**Pull request closed without merging**
