### PR TITLE
kanshu

### PR DESCRIPTION
**Pull request by 21zhouyun**

### CODE REVIEW

**Comment by 21zhouyun** [comment]
I made everything based on the design shown here https://www.dropbox.com/s/a06zzw7bz3ytxhu/02%20Kanshu%20UI%20-%20articles%20screen.png?dl=0. However, I was unable to remove the shadow below the actionbar. I tried playing around with the styling file and change the windowsContentOverlay to null but it does not work.

**Comment by intrications** [comment]
Great job! Just a few small changes and I can merge.

1. Can you make the Navigation Drawer go over the ActionBar (and possibly below the status bar) as per the Material Design guidelines?
http://www.google.co.uk/design/spec/patterns/navigation-drawer.html

2. I think ArticleFragment should be renamed ArticleListFragment.

3. I suspect you can remove the shadow by using your own Toolbar: https://developer.android.com/reference/android/support/v7/widget/Toolbar.html

But don't worry about it too much. It can be fixed later. You've done a lot already for this bounty.

**Comment by fernandobuzi** [comment]
That was fast @intrications, thanks. Especially for the heads-up on how much work was actually done. You'll need to be rewarded for the extra work, @21zhouyun. ;)

**Comment by intrications** [comment]
I have merged this in so that work can continue on bounty #107.

**Pull request merged**
