### PR TITLE
Memorization exercise (#147)

### PR DESCRIPTION
**Pull request by arandr**
The dialog doesn't match the mockup entirely, but theming dialogs to achieve a precise look is fairly difficult. I used a standard theme, but if we want more precise styling we can use a library like https://github.com/avast/android-styled-dialogs or https://github.com/afollestad/material-dialogs (assuming we want something that still looks like the Material Design ones, haven't seen any that are 100% customizable).

### CODE REVIEW

**Comment by fernandobuzi** [comment]
Thanks a lot for this @arandr. ;)

@intrications could you please go through it? Ps: just a reminder that @arandr won't be available next week.

**Comment by intrications** [comment]
@arandr @fernandobuzi 

The main problem for me is that the dialog appears immediately and covers the answers so you can't actually see which is the correct answer if you answered incorrectly. See screenshot below.

I'm going to merge this since @arandr is going away. I think we need to rethink how to display it. Maybe the dialog should show the correct answer.

If we keep the dialog then I think it does need to be customized more. However, it doesn't necessarily need one of those libraries. It just needs a custom View with our own red styled button on it.

device-2015-02-28-115012

**Comment by arandr** [comment]
@intrications you have a good point with the dialog appearing. In the complete workflow there will need to be a way to leave time after answering a question before either showing a new flashcard or the dialog. It could be as simple as a 1-2s timer, or it could be requiring some action on the part of the user to go on (a swipe gesture or "next" button in the menu) and that action would trigger showing the popup at the end of the exercise.

**Comment by intrications** [comment]
@arandr @fernandobuzi 

I actually don't think it should be a Dialog at all. It can just be a View that appears over the questions. Easier to make it partially transparent like the mockup.

**Pull request merged**
