### PR TITLE
Sliders with ticks and animations, #114

### PR DESCRIPTION
**Pull request by arandr**

### CODE REVIEW

**Comment by intrications** [comment]
Looks good so far. I will post comments once I have tested it on a small screen device as well as my Nexus 6.

**Comment by intrications** [comment]
Screenshots and video posted at: https://assembly.com/kanshu/bounties/114

I've added checkboxes here but I don't think you're actually able to tick off the items without having access to this main repo.

- [ ] For some reason the background is black on a Samsung Galaxy Young running Android 4.1.2. See if you can replicate this in an emulator otherwise I'll look into the issue.

- [ ] The background is completely transparent. It should partially block out the text behind (which I have added to test - let me know if you want me to push this bit of code to github - or you can add text yourself.

- [ ] I think you not taking into account the screen density when drawing the dots. This should also fix the slider thumb being cut off at the sides.

- [ ] Use grey rather than blue for the touch highlights.

- [ ] Open all three sliders initially when touching anywhere on the slider that is always shown. It is very hard to open when only being able to press the text at the sides. No slider should slide until all three are shown.

**Comment by arandr** [comment]
Changed to take into account screen density, changed thumb highlight color, and slider opens when touched anywhere on it. I added a blur effect to the text behind (and some sample text to show it), but let me know if you'd like it tweaked (text more/less transparent, or more/less blurry). 

Don't have a Galaxy Young but I'm thinking the background effect might be because I didn't set a fill color to the shape drawable. It's possible this particular device defaults to black and not transparent. Either way, now there is a (very subtle) fill to the background of the sliders so that shouldn't be an issue.

**Comment by intrications** [comment]
Getting closer. The opening and closing works well. It would be nice if you can fade them in as they scroll in. Otherwise it's quite jarring as they suddenly fade or unfade.

I don't think the text underneath needs to be blurred anymore but the slider should have a partially transparent white background. It is most important that the user can see the slider. Seeing the text below it is just to make the design look good. Look at the mockup. The text is quite faded.

(Note also that there is much more blur on the lower density young. Are you setting the blur in pixels without taking into account the density?)

There are still problems with the thumb and dot sizes. What device are you testing on? Are you testing on different screen sizes and densities?

Nexus 6:

device-2015-02-02-082748

Nexus 5:

device-2015-02-02-083236

Samsung Galaxy Young:

device-2015-02-02-084052

**Comment by fernandobuzi** [comment]
@arandr  @intrications I don't know if this helps, but the mockup uses a white background on 70% opacity. No blur.
So, even if the blur is nice, I'd just ignore it completely if it adds to developing time. With the background and opacity done right, the blur is not necessary.

**Comment by intrications** [comment]
@fernandobuzi That is useful information. I think that the blur should probably be removed. The white background should be enough.

**Comment by intrications** [comment]
@arandr I've looked at the code and I can't really work out what is going on with the density and why it isn't displaying correctly.

So do discuss more if you don't know either and we'll work it out.

**Comment by arandr** [comment]
Okay, I think that's all changes. 
-Fade in/out : tweaked the delays, don't want the animation to take too much time either, should be more noticeable.
-Background for slider: turned up opacity (mine was only 20%), toned down blur. 
- Thumb clipping/density problems : Clipping of thumbs should be good, was an error in the library. I *think* the same thing applies to the density (they were using getDimension() but still scaling afterwards), tell me if you have any more issues. (The size looks to be more consistent at least.)
- Blur takes into account the density.

**Comment by intrications** [comment]
Looking good. Just need to check on Samsung Galaxy Young when I get home but I think we're there!

Thanks for all your hard work.

**Comment by arandr** [comment]
Did you have the time to review this @intrications ?

**Comment by intrications** [comment]
@arandr @fernandobuzi Sorry for the delay.

Everything is fine apart from the animation.

But I will merge this for now and we can fix that later. The functionality is there and working well. Thanks!

**Pull request merged**
