### PR TITLE
Implement skeleton of 'My saved characters' screen #118

### PR DESCRIPTION
**Pull request by alouanemed**
image

### CODE REVIEW

**Comment by intrications** [comment]
Merged. I'll fix the issues with the layout.

**Comment by alouanemed** [comment]
:+1:

**Comment by intrications** [comment]
The layout of the Chinese character appears to be a problem with the font so there's nothing you did wrong.

**Comment by alouanemed** [comment]
aha, I see .well I tried to change the layout settings but I end up thinking of the same thing.

**Pull request merged**
