### PR TITLE
Created an app + signup activity.

### PR DESCRIPTION
**Pull request by arandr**

### CODE REVIEW

**Comment by 21zhouyun** [comment]
I think you missed some file. I downloaded the project. The layout xml complains that every "@color" and "@style" tag is missing a source.

**Comment by intrications** [comment]
@arandr 

I agree with @21zhouyun 

I can't even import/open it in Android Studio. Are you sure you've included all the files? Are you using Gradle wrapper? Usually there is also a settings.gradle file.

**Comment by arandr** [comment]
Right, I forgot most of the config files. I'm sorry, I just switched from Eclipse to Android Studio, and though I'm having a better experience with it I haven't tried to use it with VCS before. Added them now!

**Comment by intrications** [comment]
Can you switch to using this .gitignore file?

https://www.gitignore.io/api/android,intellij,osx,windows

This will remove the Android Studio config files which are not required in the repo.

You will probably need to remove some files that have already been added. This should tell you how: http://stackoverflow.com/a/19095988/84021

**Comment by fernandobuzi** [comment]
@arandr, pls give us a heads up when this is done.

**Comment by intrications** [comment]
@arandr Don't worry. I've updated the gitignore file. Thanks for your work on this.

**Pull request merged**
