### PR TITLE
Bounty #109

### PR DESCRIPTION
**Pull request by 21zhouyun**
https://assembly.com/kanshu/bounties/109

### CODE REVIEW

**Comment by intrications** [comment]
@21zhouyun 

1. It would probably be better to make the whole of the "23 comments" and arrow open the comments view. It is very hard to press the tiny arrow.

2. Looking at the mockup, the arrow should either be red or turn red when the comments view is shown.

3. It should possible also rotate to point downwards when the comments view opens.

4. The actual comment is not all showing. It is cut off at the bottom.

5. Can you rebase your changes on master? Let me know if you have problems doing this and I can do it for you.

@fernandobuzi What do you think about my points. Screenshot below.

screenshot_2015-01-24-17-53-36

**Comment by 21zhouyun** [comment]
I got your point. I'll start working on the change and hopefully I can make it work tonight.

**Comment by fernandobuzi** [comment]
@intrications I agree with all points. 

About the cut out comments, @21zhou was probably led to do it that way because of the mock-up. 

The idea was that the reader would view two or 3 and then scroll within the grey area to read the rest. 

But it's OK if it opens all comments at once. I don't think it makes much of a difference. ;)

**Comment by intrications** [comment]
@fernandobuzi The comments do scroll within the grey area. That is correct. But each row of the comments list needs to expand to show the whole comment text.

**Comment by 21zhouyun** [comment]
@intrications Does that mean each comment section can have different size based on the length of the comments?

**Comment by intrications** [comment]
@21zhouyun Yes, I would think so. Unless we want to make each comment expandable if it is too long. Depends how long comments can/will be.

We can't just cut off the end of the comment.

**Comment by 21zhouyun** [comment]
@intrications ok, I will implement that

**Comment by alouanemed** [comment]
@intrications  this is bounty #109 not  "107

**Comment by intrications** [comment]
@alouanemed Sorry, fixed.

**Comment by alouanemed** [comment]
@21zhouyun  make sure you Fix pull request conflicts in your next commit

**Comment by 21zhouyun** [comment]
@intrications I merged the upstream code with my local repo. However, it seems I cannot launch the ArticleActivity now without passing in an intent. How should I do that?

**Comment by intrications** [comment]
@21zhouyun Sorry, I'm not sure what you mean. Can you push your code and I'll take a look?

Does the Sign Up button not start the ArticleActivity?

**Comment by 21zhouyun** [comment]
@intrications Sorry, I tried to launch the ArticleActivity directly. It launches from the signup activity.

**Comment by intrications** [comment]
@21zhouyun So is the problem fixed? I'm going to try to add an extra activity with buttons to each of the sections during development rather than each developer taking over the sign up or other button.

**Comment by 21zhouyun** [comment]
I updated my repo with the upstream code. Try it out!

**Comment by 21zhouyun** [comment]
I also fixed all the problem you mentioned.

**Comment by intrications** [comment]
Thanks. I think it all merged in fine. I'm getting quite good at juggling different branches!

**Pull request merged**
