### PR TITLE
integrate test suite with travis

### PR DESCRIPTION
**Pull request by vsima**
- update .travis.yml 
- update android lint settings (set abortOnError false) to allow tests to finish

### CODE REVIEW

**Comment by intrications** [comment]
The Travis build is failing with these changes.

https://travis-ci.org/asm-products/kanshu-android/builds/52701421

**Comment by vsima** [comment]
see if you can restart this build. it looks like the emulator didn't unlock
the screen.

i see some travis scripts where people are appending '- sleep 20' after '-
adb shell input keyevent 82 &' in .travis.yml

'- adb shell input keyevent 82 &' unlocks the screen

**Comment by intrications** [comment]
Restarted the build and it worked.

Do you think we should add the extra sleep or wait and see how often it fails to build?

**Comment by vsima** [comment]
ok, i added the 20 sec sleep. it cant hurt

**Comment by intrications** [comment]
@vsima 

Unfortunately the build is failing (almost?) everytime, e.g. https://travis-ci.org/asm-products/kanshu-android/builds/53826038

Do you think there is a way to make this reliable? I think it might be better not to run the emulator on Travis but just run those tests on a computer.

**Pull request merged**
