### PR TITLE
Login page accessible from signup page.

### PR DESCRIPTION
**Pull request by arandr**
Added the login page. By the way, I'm on Central time, so don't worry if it takes me some time to answer comments/requests for changes.

### CODE REVIEW

**Comment by intrications** [comment]
@arandr Can you take a look at the layout in landscape and a small screen size. Only some of it is visible.

You can probably fix this by putting the layout in a ScrollView.

The signin activity should also be fixed for landscape the same way.

**Comment by arandr** [comment]
I thought of doing that, but I don't have a good experience using apps that force me to scroll starting from the login screen, so I ended up making a landscape version of the screen. Tell me what you think of it.

**Comment by intrications** [comment]
I agree that a proper landscape layout is better and that it shouldn't scroll on most screens.

However, the screens still don't work on very small screens. See the screenshots below.

It doesn't have to look amazing on these screens because they are a small percentage of the market. But the content has to be accessible.

So the easiest solution is to wrap (at least part of) the layout in a ScrollView.

Screenshot
Screenshot

**Comment by fernandobuzi** [comment]
@intrications, and what if we forced portrait mode for the Sign-up and Login screens for the MVP so that we always get the option on your first image?

**Comment by intrications** [comment]
@fernandobuzi I wouldn't support that. Some Android devices only work in landscape. Let's embrace the flexibility of Android by supporting all screen sizes and orientations.

A ScrollView is a simple solution that most users will never see anyway but covers the edge cases.

And if you look closely, the portrait screenshot is actually the one with the bigger problem. It is missing the Spinner below the Username field.

**Comment by fernandobuzi** [comment]
I get it. Ok then. 

@arandr, for the landscape I'd suggest both the logo and the text on the left. Not split like you suggested. It feels more balanced and in line with the portrait mode.

**Comment by arandr** [comment]
Added a few modifications. @fernandobuzi, I changed the image position so that it's on the left too. @intrications, should work well for small-to-medium screen sizes, though I think we'll need to add another layout for tablets (it's looking somewhat empty).

**Comment by intrications** [comment]
Thanks. That looks great.

Don't worry about tablets too much, it's just worth having a glance to check it isn't a complete mess. A bit empty can be fixed easily.

**Pull request merged**
